### ISSUE TITLE
When added github project

### ISSUE THREAD

**Issue by shahnawazm786** [shahnawazm786/MyJavaResporatory#1]
[RemoteTestNG] detected TestNG version 7.3.0
org.testng.TestNGException: 
Cannot find class in classpath: com.gitjenkinsdemo.NewTest
	at org.testng.xml.XmlClass.loadClass(XmlClass.java:75)
	at org.testng.xml.XmlClass.init(XmlClass.java:67)
	at org.testng.xml.XmlClass.<init>(XmlClass.java:54)
	at org.testng.xml.TestNGContentHandler.startElement(TestNGContentHandler.java:556)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.emptyElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
	at javax.xml.parsers.SAXParser.parse(Unknown Source)
	at org.testng.xml.XMLParser.parse(XMLParser.java:39)
	at org.testng.xml.SuiteXmlParser.parse(SuiteXmlParser.java:16)
	at org.testng.xml.SuiteXmlParser.parse(SuiteXmlParser.java:9)
	at org.testng.xml.Parser.parse(Parser.java:162)
	at org.testng.xml.Parser.parse(Parser.java:248)
	at org.testng.TestNG.parseSuite(TestNG.java:322)
	at org.testng.TestNG.initializeSuitesAndJarFile(TestNG.java:374)
	at org.testng.TestNG.initializeEverything(TestNG.java:1017)
	at org.testng.remote.support.RemoteTestNG6_12.initialize(RemoteTestNG6_12.java:22)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:98)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

**Comment by shahnawazm786** [comment]
Clean the project (Right click on pom.xml and clean)
And update the maven project (Project > Maven > Update Maven Project)

**Comment by shahnawazm786** [comment]
I just follow the following step.
Issue has been fixed.
Clean the project (Right click on pom.xml and clean)
And update the maven project (Project > Maven > Update Maven Project)
Thanks, it is solved immediately
